### ISSUE TITLE
Show unused crates in crates.parity.io

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/docs#88]
Crates like srml-example and srml-assets are not shown in crates.parity.io because they are not included in any of the projects.

How can we fix this?

**Comment by folsen** [comment]
I have a related question here; how useful is it to have the dependency docs in here? To me it's super confusing because it makes the substrate-specific crates really hard to find. If I want the docs for `ansi_term` I would go to the `ansi_term` docs on docs.rs, I wouldn't really look for it in the substrate crates docs.

**Comment by thiolliere** [comment]
I'm not sure about the interest of having srml-example in the doc as its rustdoc are mostly guidelines to write doc for modules (but this could be moved). and some interesting stuff are actually inlined documentation.

But srml-assets seems to deserve being in the rustdoc.

About having dependency docs here it might be better to keep them here as docs are linked together using relative path (except std)

**Comment by thiolliere** [comment]
I would expect doc to be compiled there https://github.com/paritytech/substrate/blob/029a778243e79de872e85e01823f6806876febe0/.gitlab-ci.yml#L181

we should add `--all --exclude srml-example` maybe

**Comment by shawntabrizi** [comment]
Solved
